FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /gw_server ./cmd/server

FROM alpine:latest

COPY --from=builder /gw_server /gw_server

EXPOSE 8080
CMD ["/gw_server"]