FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /ai_server ./cmd/server

FROM alpine:latest

COPY --from=builder /ai_server /ai_server

EXPOSE 3003
CMD ["/ai_server"]