FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /doc_server ./cmd/server

FROM alpine:latest

COPY --from=builder /doc_server /doc_server

EXPOSE 3002
CMD ["/doc_server"]